
#MariaDB is needed for the plugin to work
mariaDB:
  host: localhost
  port: 3306
  database: bank
  username: user
  password: password

# Balance message
BalanceMessage: "Your Balance is $%Bal%"

# Placeholders
# %Deposit% is the amount you deposit
# %Withdraw% is the amount you withdraw
# %Minimum% is the MinimumAmount

Deposit:
  DepositMessage: "You have deposited $%Deposit%"
  DontHaveEnoughInBalance: "You don't have $%Deposit% in your balance"
  MinimumDepositMessage: "Minimum deposit amount is $%Minimum%"

Withdraw:
  WithdrawMessage: "You have withdrawn $%Withdraw%"
  DontHaveEnoughInBalance: "You don't have $%Withdraw% in your bank balance"
  MinimumWithdrawMessage: "Minimum withdraw amount is $%Minimum%"

#Minimum amount for deposit/withdraws
MinimumAmount: "1000"

# Player Doesn't have permission to run that command
NoPermission: "You don't have permission to run this command"

# You can't run that command
YouCantRunThis: "Only Players can run this"