mysql:
  host: localhost
  port: 3306
  database: bank
  username: user
  password: password

# Player Doesn't have permission to run that command
NoPermission: "&cYou don't have permission to run this command"

# You can't run that command
YouCantRunThis: "&cYou can't run this"

BalanceMessage: "&aYour balance is $"

DepositMessage: "&aYou have deposited $"

DontHaveEnoughInBalance: "You don't have $%Deposit% in your balance"

WithdrawMessage: "&aYou have withdraw $%Withdraw%"

MinimumAmount: "1000"