reload-message: "&aConfig Reloaded"
deposit-message: "&aSuccessfully Deposted <amount>"
withdraw-message: "&aaSuccessfully Withdraw <amount>"
balance-message: "&aBalance <amount>"

#MySql
mysql:
  host: localhost
  port: 3306
  database: Bank
  user: user
  password: password